replicaCount: 2

image:
  # Replace with your Google Artifact Registry / GCR path
  # e.g., us-central1-docker.pkg.dev/YOUR-PROJECT-ID/YOUR-REPO/web-calculator
  repository: YOUR-PROJECT-ID/web-calculator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "gce" # Standard Ingress class for Google Kubernetes Engine (GKE)
  annotations:
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/ingress.global-static-ip-name: "web-calculator-ip"
    # networking.gke.io/managed-certificates: "web-calculator-cert"
  hosts:
    - host: calculator.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
